all: war 

.PHONY: war 
war:
	@mvn war:war

.PHONY: compile
compile:
	@mvn compile

.PHONY: javadoc
javadoc:
	@mvn javadoc:javadoc

.PHONY: checkstyle
checkstyle:
	@mvn checkstyle:checkstyle 

.PHONY: clean
clean:
	@mvn clean
